#!/usr/bin/env node
import path from "node:path";
import { fileURLToPath } from "node:url";
import { access, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { parseArgs } from "./args.js";
import { programInput } from "./input.js";
import { checkProgram } from "../checker.js";
import { loadConfig } from "../config.js";
import { executeProgram } from "../runtime/executor.js";
import { errorObject, exitCode, FabricError } from "../errors.js";
import { getDocs } from "../docs.js";
import { KiroHeadlessRunner, runProcess } from "../runners/kiro.js";
import { installKiro, validateInstalled } from "../installer.js";
import { parseFramed } from "../runners/parser.js";
const usage=`fabric-lite <check|exec|docs|models|doctor|install-kiro> [options]`;
function output(value:unknown,format:"json"|"text"){process.stdout.write(format==="json"?JSON.stringify(value)+"\n":typeof value==="string"?value+"\n":JSON.stringify(value,null,2)+"\n");}
async function doctor(cwd:string,format:"json"|"text",smoke:boolean){const config=await loadConfig(cwd),runner=new KiroHeadlessRunner(config.runner.executable,config.runner.workerAgent),checks:any[]=[];const nodeMajor=Number(process.versions.node.split(".")[0]);checks.push({name:"node",ok:nodeMajor>=20,detail:process.version});try{await access(fileURLToPath(new URL("../../types/fabric-lite.d.ts",import.meta.url)));checks.push({name:"package-integrity",ok:true,detail:"CLI and declarations available"});}catch(e){checks.push({name:"package-integrity",ok:false,detail:(e as Error).message});}const d=await runner.doctor();checks.push({name:"kiro",ok:d.ok,detail:d.version??d.message});try{const r=await runProcess(config.runner.executable,["whoami"],{timeoutMs:15000});checks.push({name:"authentication",ok:r.exitCode===0,detail:r.exitCode===0?"authenticated":"run kiro-cli login"});}catch(e){checks.push({name:"authentication",ok:false,detail:(e as Error).message});}try{const h=await runProcess(config.runner.executable,["chat","--help"],{timeoutMs:10000});checks.push({name:"headless",ok:h.exitCode===0&&h.stdout.includes("no-interactive"),detail:"chat --no-interactive"});}catch(e){checks.push({name:"headless",ok:false,detail:(e as Error).message});}const agents=await validateInstalled(config.runner.executable,cwd);checks.push({name:"agents",ok:agents.every(x=>x.ok),detail:agents});const temp=await mkdtemp(path.join(tmpdir(),"fabric-lite-doctor-"));try{await writeFile(path.join(temp,"ok"),"ok");checks.push({name:"temporary-directory",ok:true,detail:temp});}finally{await rm(temp,{recursive:true,force:true});}try{const g=await runProcess("git",["rev-parse","--show-toplevel"],{timeoutMs:5000,cwd});checks.push({name:"project-root",ok:g.exitCode===0,detail:g.stdout.trim()||path.resolve(cwd)});}catch{checks.push({name:"project-root",ok:true,detail:path.resolve(cwd)});}if(smoke){try{const raw=await runner.run({instruction:'Return {"ok":true}.',context:"",role:"general",schema:{type:"object",properties:{ok:{const:true}},required:["ok"],additionalProperties:false},maxOutputChars:1000,timeoutMs:config.budgets.aiCallTimeoutMs});parseFramed(raw.stdout,{type:"object",properties:{ok:{const:true}},required:["ok"],additionalProperties:false},1000);checks.push({name:"paid-semantic-smoke",ok:true});}catch(e){checks.push({name:"paid-semantic-smoke",ok:false,detail:(e as Error).message});}}else checks.push({name:"paid-semantic-smoke",ok:true,detail:"skipped; pass --smoke to opt in"});const report={version:1,status:checks.every(x=>x.ok)?"healthy":"unhealthy",checks};output(report,format);if(report.status!=="healthy")process.exitCode=3;}
async function main(){const args=parseArgs(process.argv.slice(2));switch(args.command){case"check":{const body=await programInput(args.file),result=checkProgram(body);const envelope={version:1,status:result.ok?"valid":"failed",diagnostics:result.diagnostics};output(envelope,args.format);if(!result.ok)process.exitCode=2;break;}case"exec":{const body=await programInput(args.file),checked=checkProgram(body);if(!checked.ok){output({version:1,runId:"none",status:"failed",error:{code:"TYPECHECK_FAILED",message:"Program failed type checking",diagnostics:checked.diagnostics}},args.format);process.exitCode=2;break;}const config=await loadConfig(args.cwd),run=await executeProgram(body,config);output(run.envelope,args.format);process.exitCode=run.exitCode;break;}case"docs":output(getDocs(args.topic,args.compact),args.format);break;case"models":{const config=await loadConfig(args.cwd),runner=new KiroHeadlessRunner(config.runner.executable,config.runner.workerAgent);output({version:1,models:await runner.listModels()},args.format);break;}case"doctor":await doctor(args.cwd,args.format,args.smoke);break;case"install-kiro":{const config=await loadConfig(args.cwd);const cli=fileURLToPath(import.meta.url);const result=await installKiro({root:path.resolve(args.cwd),cliPath:cli,executable:config.runner.executable,force:args.force,dryRun:args.dryRun});output(result,args.format);break;}default:process.stderr.write(usage+"\n");process.exitCode=3;}}
main().catch(e=>{const err=errorObject(e);output({version:1,status:"failed",error:err},process.argv.includes("json")?"json":"text");process.exitCode=e instanceof FabricError?exitCode(e.code):3;});