import { spawn } from "node:child_process";
import { appendFile } from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";
import type { AiRunner, ModelInfo, NormalizedAiRequest, RawAiRunnerResult, RunnerDoctorResult } from "./types.js";
import { FabricError } from "../errors.js";
import { framePrompt } from "./parser.js";
const KIRO_ENV_KEYS = [
 "HOME","PATH","USER","LOGNAME","SHELL","TMPDIR","TEMP","TMP","XDG_CONFIG_HOME","XDG_CACHE_HOME","XDG_DATA_HOME",
 "KIRO_API_KEY","KIRO_CLI_PATH","AWS_PROFILE","AWS_REGION","AWS_DEFAULT_REGION","AWS_ACCESS_KEY_ID","AWS_SECRET_ACCESS_KEY",
 "AWS_SESSION_TOKEN","AWS_CONFIG_FILE","AWS_SHARED_CREDENTIALS_FILE","AWS_SDK_LOAD_CONFIG","AWS_WEB_IDENTITY_TOKEN_FILE","AWS_ROLE_ARN"
] as const;
/** A value-preserving allowlist used for both the execution worker and Kiro itself. Never log this object. */
export function filteredKiroEnv(extra: NodeJS.ProcessEnv = {}): NodeJS.ProcessEnv { const out: NodeJS.ProcessEnv = { NO_COLOR: "1", KIRO_LOG_NO_COLOR: "1" }; for (const k of KIRO_ENV_KEYS) if (process.env[k] !== undefined) out[k] = process.env[k]; return { ...out, ...extra }; }
export async function runProcess(command: string, args: string[], options: { timeoutMs: number; maxChars?: number; signal?: AbortSignal; cwd?: string } ): Promise<RawAiRunnerResult> { return await new Promise((resolve, reject) => { const started = Date.now(); const child = spawn(command, args, { cwd: options.cwd, env: filteredKiroEnv(), detached: process.platform !== "win32", stdio: ["ignore","pipe","pipe"] }); let stdout = "", stderr = "", exceeded: "stdout"|"stderr"|undefined, timedOut = false; const cap = options.maxChars ?? 100_000; const kill = () => { try { if (process.platform !== "win32" && child.pid) process.kill(-child.pid, "SIGKILL"); else child.kill("SIGKILL"); } catch {} }; const add = (which: "stdout"|"stderr", chunk: Buffer) => { const text = chunk.toString("utf8"), current = which === "stdout" ? stdout : stderr, remaining = Math.max(0, cap - current.length); if (which === "stdout") stdout += text.slice(0, remaining); else stderr += text.slice(0, remaining); if (text.length > remaining && !exceeded) { exceeded = which; kill(); } }; child.stdout.on("data", (c: Buffer) => add("stdout", c)); child.stderr.on("data", (c: Buffer) => add("stderr", c)); const timer = setTimeout(() => { timedOut = true; kill(); }, options.timeoutMs); const onAbort = () => kill(); options.signal?.addEventListener("abort", onAbort, { once: true }); if (options.signal?.aborted) onAbort(); child.on("error", e => { clearTimeout(timer); options.signal?.removeEventListener("abort", onAbort); reject(e); }); child.on("close", code => { clearTimeout(timer); options.signal?.removeEventListener("abort", onAbort); if (timedOut) return reject(new FabricError("TIMEOUT", `Process timed out after ${options.timeoutMs}ms`)); if (options.signal?.aborted) return reject(new FabricError("CANCELLED", "Operation cancelled")); if (exceeded) return reject(new FabricError("RUNTIME_FAILED", `Child process ${exceeded} limit of ${cap} characters exceeded`)); resolve({ stdout, stderr, exitCode: code ?? 1, elapsedMs: Date.now() - started }); }); }); }
export class KiroHeadlessRunner implements AiRunner { readonly name = "kiro-headless"; constructor(readonly executable = process.env.KIRO_CLI_PATH ?? "kiro-cli", readonly agent = "fabric-lite-worker") {} async doctor(): Promise<RunnerDoctorResult> { try { const r = await runProcess(this.executable, ["--version"], { timeoutMs: 10000 }); return { ok: r.exitCode === 0, name: this.name, version: (r.stdout || r.stderr).trim().slice(0,200) }; } catch (e) { return { ok: false, name: this.name, message: (e as Error).message }; } } async listModels(): Promise<ModelInfo[]> { const r = await runProcess(this.executable, ["chat","--list-models","--format","json"], { timeoutMs: 20000 }); if (r.exitCode !== 0) throw new FabricError("CONFIG_ERROR", `Kiro model enumeration failed (exit ${r.exitCode}): ${r.stderr.trim().slice(-500)}`); let parsed: unknown; try { parsed=JSON.parse(r.stdout); } catch (e) { throw new FabricError("CONFIG_ERROR", `Kiro model enumeration returned invalid JSON: ${(e as Error).message}; output: ${r.stdout.trim().slice(0,300)}`); } const list = Array.isArray(parsed) ? parsed : parsed && typeof parsed === "object" && Array.isArray((parsed as { models?: unknown }).models) ? (parsed as { models: unknown[] }).models : undefined; if (!list) throw new FabricError("CONFIG_ERROR","Kiro model enumeration JSON must be an array or an object with a models array"); return list.map((x: unknown) => { if (typeof x === "string") return { id: x }; const item=x as { id?:unknown;name?:unknown;model_id?:unknown;model_name?:unknown;description?:unknown }; const id=item.id??item.model_id??item.name??item.model_name; if (typeof id !== "string") throw new FabricError("CONFIG_ERROR","Kiro returned an unrecognized model entry"); const name=item.name??item.model_name; return { id, ...(typeof name === "string" ? { name } : {}), ...(typeof item.description === "string" ? { description:item.description } : {}) }; }); } async run(request: NormalizedAiRequest, signal?: AbortSignal): Promise<RawAiRunnerResult> { const args = ["chat","--no-interactive","--agent",this.agent]; if (request.model) args.push("--model",request.model); args.push(framePrompt(request)); const r = await runProcess(this.executable, args, { timeoutMs: request.timeoutMs, maxChars: request.maxOutputChars * 3 + 10000, ...(signal ? { signal } : {}) }); if (process.env.FABRIC_LITE_RUN_DIR) await appendFile(path.join(process.env.FABRIC_LITE_RUN_DIR,"calls.jsonl"),JSON.stringify({at:new Date().toISOString(),role:request.role,repair:request.repair??false,model:request.model??null,inputChars:request.instruction.length+request.context.length+JSON.stringify(request.schema??{}).length,outputChars:r.stdout.length,elapsedMs:r.elapsedMs,exitCode:r.exitCode,instructionSha256:createHash("sha256").update(request.instruction).digest("hex")})+"\n"); if (r.exitCode !== 0) throw new FabricError("RUNTIME_FAILED", `Kiro exited ${r.exitCode}: ${r.stderr.slice(-1000)}`); return r; } }