import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';import {createKiroRuntime,normalizeFabricConfig} from '../../dist/index.js';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'kiro-efficiency-local-'));const rows=[];const events=[];let seq=0;
const tracer={enabled:true,event(cat,ev,execId,data){events.push({cat,ev,execId,data});},span(cat,ev,execId,data,parentId){const start=performance.now();const id=`span-${++seq}`;return {id,end(endData){events.push({cat,ev,execId,parentId,spanId:id,durUs:(performance.now()-start)*1000,data:{...data,...endData}})}};},flush(){},close(){}};
const runtime=createKiroRuntime({cwd:root,configFile:path.join(root,'absent.json'),mcpConfigPath:path.join(root,'absent-mcp.json'),artifactsRoot:path.join(root,'artifacts'),config:normalizeFabricConfig({mcp:{enabled:false}})});
try{
 const artifact=runtime.artifacts.write('x'.repeat(120000));
 const code='const x = await artifacts.read({id: payloads.id}); if (x === null || typeof x !== "object" || Array.isArray(x) || typeof x.text !== "string") throw new Error("unexpected artifact shape"); return {length:x.text.length, sample:x.text.slice(0,8)};';
 const execute=async(name,code,payloads={id:artifact})=>{const start=performance.now();const result=await runtime.service.execute({code,payloads,tracer,approver:{async approve(action){assert.equal(action.risk,'read');}}});rows.push({name,timestamp:new Date().toISOString(),status:result.status,success:result.success,elapsedMs:performance.now()-start,value:result.value??null,error:result.error??null,typeErrors:result.typeErrors??null,nestedCalls:result.audits.length});return result;};
 for(let i=0;i<6;i++){const r=await execute(i===0?'cold':'warm-'+i,code);assert.equal(r.success,true);assert.deepEqual(r.value,{length:12000,sample:'xxxxxxxx'});}
 const failure=await execute('recoverable-failure','return await artifacts.read({id:payloads.id});',{id:`ka_${'a'.repeat(48)}`});assert.equal(failure.success,false);assert.match(failure.error,/unavailable|expired/);
 const recovered=await execute('recovered',code);assert.equal(recovered.success,true);assert.equal(recovered.value.length,12000);
 const summary={kind:'built-library-local-probe-not-Kiro',pid:process.pid,baselineOnly:true,runtimeInstances:1,guestExecutions:rows.length,assertionsPassed:true,sourceArtifactChars:120000,largeNestedTextChars:12000,compactReturnedJsonChars:JSON.stringify(recovered.value).length,rows,events,hostRequests:null,inputTokens:null,credits:null,billedSpend:null};
 fs.writeFileSync('audits/efficiency-2026-09-05/runtime-probe-results.json',JSON.stringify(summary,null,2));console.log(JSON.stringify({assertionsPassed:true,rows,compactReturnedJsonChars:summary.compactReturnedJsonChars}));
}catch(error){fs.writeFileSync(`audits/efficiency-2026-09-05/runtime-probe-failed-${Date.now()}.json`,JSON.stringify({rows,events,error:String(error)},null,2));throw error;}finally{await runtime.close();fs.rmSync(root,{recursive:true,force:true});}
