import path from "node:path";

import { resolveKiroProjectRoot } from "./managed.js";
import { verifyCanonicalKiroProjectRootIdentity } from "./project-root-identity.js";

export interface KiroMcpLaunchEnvironment {
  cwd: string;
  toolsEnv?: string;
  kind: "managed-main" | "internal-child";
}

/**
 * Resolve only profile-owned Kiro launch variables. A managed-main session
 * roots its tool sandbox at the working directory where kiro-cli was actually
 * launched (processCwd), so Fabric can reach the files the user is working on.
 * Profiles carrying trusted shell, subagent, or tool-auto-approval grants must
 * launch at or beneath their recorded project root; selecting a user profile
 * from another repository fails before the runtime starts. CWD and child-tool
 * scoping are accepted solely from the isolated internal-child profile
 * generated by run-profile.ts.
 */
export const resolveKiroMcpLaunchEnvironment = (
  env: NodeJS.ProcessEnv = process.env,
  processCwd = process.cwd(),
): KiroMcpLaunchEnvironment => {
  if (env.KIRO_FABRIC_PROFILE_KIND !== "internal-child") {
    // Prefer the launch directory: kiro-cli spawns the MCP child from the
    // user's current working directory. If that directory disappeared before
    // MCP startup, retain the managed install root as a compatibility fallback.
    const configuredRoot = env.KIRO_FABRIC_PROJECT_ROOT;
    const confined =
      env.KIRO_FABRIC_ENFORCE_PROJECT_ROOT === "1" ||
      env.KIRO_FABRIC_ALLOW_SHELL === "1" ||
      env.KIRO_FABRIC_ENABLE_SUBAGENTS === "1" ||
      env.KIRO_FABRIC_ALLOW_TOOLS === "1";
    let cwd: string;
    try {
      cwd = resolveKiroProjectRoot(processCwd);
    } catch {
      cwd = resolveKiroProjectRoot(
        configuredRoot ?? processCwd,
      );
    }
    if (confined) {
      if (!configuredRoot) {
        throw new Error(
          "trusted Kiro profile is missing its canonical project root; " +
            "reinstall the profile with --project-root",
        );
      }
      const expectedDev = env.KIRO_FABRIC_PROJECT_ROOT_DEV;
      const expectedIno = env.KIRO_FABRIC_PROJECT_ROOT_INO;
      if (!expectedDev || !expectedIno) {
        throw new Error(
          "trusted Kiro profile is missing its project identity; " +
            "reinstall the profile",
        );
      }
      const root = verifyCanonicalKiroProjectRootIdentity(configuredRoot, {
        dev: expectedDev,
        ino: expectedIno,
      }).root;
      const relative = path.relative(root, cwd);
      if (
        relative === ".." ||
        relative.startsWith(`..${path.sep}`) ||
        path.isAbsolute(relative)
      ) {
        throw new Error(
          `trusted Kiro profile is confined to ${root}; ` +
            `launching kiro-cli from ${cwd} is outside that project. ` +
            `Run kiro-cli from inside ${root} (or a subdirectory of it), ` +
            `or reinstall the profile (kiro-fabric install kiro --user ` +
            `--project-root \"${root}\") for a different project.`,
        );
      }
    }
    return { cwd, kind: "managed-main" };
  }
  const childCwd = env.KIRO_FABRIC_CWD;
  const toolsEnv = env.KIRO_FABRIC_KIRO_TOOLS;
  if (!childCwd || toolsEnv === undefined) {
    throw new Error("internal Kiro child profile is missing its canonical cwd or tool scope");
  }
  // The worker validates whether this cwd belongs to the project or its
  // explicitly selected worktree before generating the internal profile.
  const cwd = resolveKiroProjectRoot(childCwd);
  return { cwd, toolsEnv, kind: "internal-child" };
};
