#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const repositoryRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const expectedFiles=["dist/index.js","dist/chunks/*.js","dist/runtime/compiler-worker-entry.js","dist/**/*.d.ts","!dist/kiro-agent-closure/**/*","docs/architecture.md","docs/audit.md","docs/configuration.md","docs/release.md","docs/tracing.md","README.md","STATUS.md","SECURITY.md","LICENSE","THIRD_PARTY_NOTICES.md"];
const exact=new Set(["package.json",...expectedFiles.filter(f=>!f.includes("*"))]);
export const isPackedPackageFileAllowed=(file)=>typeof file==="string"&&!file.includes("\\")&&!file.split("/").some(p=>!p||p==="."||p==="..")&&(exact.has(file)||/^dist\/chunks\/[^/]+\.js$/u.test(file)||(file.startsWith("dist/")&&file.endsWith(".d.ts")&&!file.startsWith("dist/kiro-agent-closure/")));
export const assertPackagePolicy=(root=repositoryRoot)=>{const pkg=JSON.parse(fs.readFileSync(path.join(root,"package.json"),"utf8")),product=JSON.parse(fs.readFileSync(path.join(root,"agent-product.json"),"utf8"));if(pkg.bin!==undefined)throw new Error("The library-only npm package must not publish an Agent wrapper");if(!String(pkg.description).startsWith("Library API for Kiro Fabric;"))throw new Error("npm package must state its library-only contract");if(pkg.main!=="./dist/index.js"||pkg.types!=="./dist/index.d.ts")throw new Error("package exports drifted");if(JSON.stringify(pkg.files)!==JSON.stringify(expectedFiles))throw new Error("published file allowlist drifted");if(product.product!=="kiro-fabric-agent"||product.entrypoint!=="src/kiro/mcp-entry.ts"||product.outputBundle!=="dist/kiro-agent-closure")throw new Error("Agent contract drifted");if(JSON.stringify(Object.keys(pkg.dependencies??{}).sort())!==JSON.stringify([...product.allowedPackageDependencies].sort()))throw new Error("dependencies drifted");for(const stale of ["plugin.json","mcp.json","power-product.json"])if(fs.existsSync(path.join(root,stale)))throw new Error(`legacy Power manifest remains: ${stale}`);const agents=path.join(root,".kiro","agents");if(fs.existsSync(agents)){for(const entry of fs.readdirSync(agents)){if(entry==="kiro-fabric"||entry.startsWith("kiro-fabric."))throw new Error(`discoverable checkout Agent would shadow the global install: ${path.join(agents,entry)}`)}}};
if(process.argv[1]===fileURLToPath(import.meta.url))assertPackagePolicy();
