import { removeFixture as rm } from "../fixture-cleanup.mjs";
// Fixtures and expectations derived from pi-fovea b5944838 (MIT).
// The embedded corpus keeps this test independent of any sibling checkout.
import { afterEach, expect, it } from 'vitest';
import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { FoveaEngine, type NavigationResult } from '../../src/fovea/engine.js';
const parser = { path: resolve('.tmp/fovea-parser/ast-grep'), sha256: '7a5ab30160186184c0bf8bffc87da4af25123c183964cd98c11b0b354137db0a', version: '0.45.3' };
const SOURCES: Record<string, string> = {
  "app/(shop)/reports/page.tsx": "export default function ReportsPage() {\n  return null;\n}\n",
  "app/api/orders/route.ts": "export async function GET() {\n  return Response.json([]);\n}\n\nexport async function POST(req: Request) {\n  return Response.json({ ok: true });\n}\n",
  "contracts/users.proto": "syntax = \"proto3\";\n\npackage users.v1;\n\n// service Guessed { rpc Wrong(Ghost) returns (Ghost); }\n/* message Ghost { string value = 1; } */\nservice Users {\n  rpc GetUser(GetUserRequest) returns (User);\n}\n\nmessage GetUserRequest { string id = 1; }\nmessage User { string id = 1; }\nmessage UserList {\n  repeated User users = 1;\n  optional User featured = 2;\n  map<string, User> by_id = 3;\n}\n",
  "openapi.yaml": "openapi: 3.0.0\npaths:\n  /api/users/{id}:\n    get:\n      summary: Load a user\n  /api/users:\n    post:\n      summary: Create a user\n",
  "pages/api/health.ts": "export default function handler(_req: unknown, res: { status: (n: number) => unknown }) {\n  res.status(200);\n}\n",
  "server/api/session.get.ts": "// @ts-nocheck — fixture: defineEventHandler is Nuxt auto-import sugar\nexport default defineEventHandler(() => ({ ok: true }));\n",
  "server/App.kt": "package demo\n\nfun Application.configureRouting() {\n  routing {\n    get(\"/ktor-ping\") { call.respond(\"pong\") }\n    post(\"/ktor-hook\") { call.respond(HttpStatusCode.OK) }\n  }\n}\n",
  "server/config.go": "package server\n\nimport \"os\"\n\nfunc DatabaseURL() string {\n\treturn os.Getenv(\"DATABASE_URL\")\n}\n",
  "server/hono.ts": "// Hono-style route registration: verb methods, method-overload `.on`,\n// mounts, and shapes that must fail closed (arrays, non-HTTP verbs).\nconst app: any = {};\n\napp.get(\"/posts\", (c: unknown) => c);\napp.on(\"PUT\", \"/posts/:id\", (c: unknown) => c);\napp.on(\"GET\", [\"/a\", \"/b\"], (c: unknown) => c);\napp.all(\"/wild\", (c: unknown) => c);\napp.use(\"/middleware\", (c: unknown) => c);\napp.on(\"PURGE\", \"/purge\", (c: unknown) => c);\n\nexport default app;\n",
  "server/main.go": "package main\n\nimport (\n\t\"os\"\n\n\t\"github.com/acme/app/server\"\n)\n\nfunc main() {\n\tdb := os.Getenv(\"DATABASE_URL\")\n\tr := NewRouter(db)\n\tr.GET(\"/api/users/:id\", server.GetUserHandler)\n\tr.POST(\"/api/users\", server.CreateUserHandler)\n\tr.Run(\":8080\")\n}\n\nfunc NewRouter(db string) *Router { return &Router{db: db} }\n\ntype Router struct{ db string }\n\nfunc (r *Router) GET(path string, h interface{}) {}\nfunc (r *Router) POST(path string, h interface{}) {}\nfunc (r *Router) Run(addr string) {}\n",
  "server/mux.go": "package server\n\nimport \"net/http\"\n\nfunc registerSysRoutes() {\n\tmux := http.NewServeMux()\n\tmux.HandleFunc(\"GET /healthz\", healthCheck)\n\tmux.HandleFunc(\"POST /v2/shutdown\", shutdownServer)\n}\n\nfunc registerApiRoutes() {\n\tr := chi.NewRouter()\n\tr.Method(\"GET\", \"/api/metrics\", http.HandlerFunc(metricsPage))\n}\n\nfunc healthCheck(w http.ResponseWriter, r *http.Request)  {}\nfunc shutdownServer(w http.ResponseWriter, r *http.Request) {}\nfunc metricsPage(w http.ResponseWriter, r *http.Request)    {}\n",
  "server/orpc.ts": "// oRPC-style procedure declarations rooted at the `os` builder identifier.\nconst os: any = {\n  route: (handler: unknown) => handler,\n  handler: (handler: unknown) => handler,\n  input: () => os,\n  router: (members: Record<string, unknown>) => members,\n};\n\nexport const planetRouter = os.router({\n  ping: os.route(async () => \"pong\"),\n  pong: os.handler(() => \"ping\"),\n  echo: os.input(\"schema\").handler(({ input }: { input: unknown }) => input),\n});\n\nexport const listPlanet = os.planet.list\n  .handler(async ({ input }: { input: unknown }) => input);\nexport const findPlanet: unknown = os.input(\"schema\").handler(() => null);\n\n// Negative: receivers not rooted at `os` stay unanchored.\nexport const detached = os.input(\"schema\");\nexport const detachedHandler = detached.handler(() => \"detached\");\nconst wrongBuilder = { route: (handler: unknown) => handler };\nexport const wrongRoot = wrongBuilder.route(async () => \"wrong\");\n",
  "server/router.ex": "defmodule Demo.Router do\n  use Phoenix.Router\n\n  scope \"/api\" do\n    get \"/elixir-health\", HealthController, :show\n    post \"/elixir-events\", EventsController, :create\n  end\n\n  forward \"/ops\", OpsRouter\nend\n",
  "server/routes.rb": "Rails.application.routes.draw do\n  get \"/up\", to: \"health#show\"\n  get \"/mystatus\", to: \"health#status\"\n  match \"/webhook\", to: \"hooks#receive\", via: [:post, :put]\nend\n",
  "server/schema.graphql": "# query Guessed { ghost }\n\"\"\"type Ghost { value: String }\"\"\"\ntype Query {\n  user(id: ID!, filter: UserFilter): User\n}\n\ninput UserFilter {\n  active: Boolean!\n}\n\ntype Subscription {\n  userChanged: User\n}\n\nenum UserRole { ADMIN USER }\nscalar DateTime\ninterface Timestamped { createdAt: DateTime }\nunion UserResult = User | NotFound\ntype NotFound { message: String }\ntype User implements Timestamped {\n  id: ID!\n  role: UserRole\n  createdAt: DateTime\n}\n",
  "server/SpringUsersController.java": "package demo.api;\n\nimport org.springframework.web.bind.annotation.*;\n\n@RestController\n@RequestMapping(\"/api/spring\")\npublic class SpringUsersController {\n    @GetMapping(\"/ping\")\n    public String ping() {\n        return \"pong\";\n    }\n\n    @PostMapping(\"/save\")\n    public void save() {}\n}\n",
  "server/trpc.ts": "interface Procedure {\n  query: (handler: () => unknown) => unknown;\n  mutation: (handler: () => unknown) => unknown;\n  input: (schema?: unknown) => Procedure;\n}\n\nconst publicProcedure: Procedure = {\n  query: (handler: () => unknown) => handler,\n  mutation: (handler: () => unknown) => handler,\n  input: () => publicProcedure,\n};\n\nconst t = { procedure: publicProcedure };\nconst router = (procedures: object) => procedures;\n\nexport const appRouter = router({\n  loadUser: publicProcedure.query(() => ({ id: \"fixture-user\" })),\n  createUser: t.procedure.input(\"schema\").mutation(() => ({ id: \"new-user\" })),\n});\n",
  "server/users.go": "package server\n\nimport \"fmt\"\n\nfunc GetUserHandler(id string) string {\n\treturn LoadUser(id)\n}\n\nfunc CreateUserHandler(name string) error {\n\treturn SaveUser(name)\n}\n\nfunc LoadUser(id string) string {\n\tfmt.Println(\"/api/users/\" + id)\n\treturn id\n}\n\nfunc SaveUser(name string) error { return nil }\n",
  "src/routes/channels/[name]/+server.ts": "export async function GET() {\n  return new Response(\"[]\");\n}\n",
  "web/airports.controller.ts": "// @ts-nocheck — fixture text: extractor parses this, tsc only lints\nimport { Controller, Get, Param, Query } from \"@nestjs/common\";\n\n@Controller('api/airports')\nexport class AirportsController {\n  @Get('search')\n  search(@Query('q') q?: string): string[] {\n    return q ? [q] : [];\n  }\n\n  @Get(':iata')\n  find(@Param('iata') iata: string) {\n    return { iata };\n  }\n}\n",
  "web/api.test.ts": "import { loadUser, createUser } from \"./api\";\n\nexport async function testLoadUser() {\n\tconst u = await loadUser(\"1\");\n\tif (!u.name) throw new Error(\"no name\");\n\tawait createUser(\"x\");\n}\n",
  "web/api.ts": "import { UserName } from \"./types\";\n\nexport interface User {\n\tid: string;\n\tname: UserName;\n}\n\nexport async function loadUser(id: string): Promise<User> {\n\tconst res = await fetch(`/api/users/${id}`);\n\treturn res.json();\n}\n\nexport async function createUser(name: string): Promise<User> {\n\tconst res = await fetch(\"/api/users\", { method: \"POST\" });\n\treturn res.json();\n}\ndeclare const axios: { get: (url: string) => Promise<unknown> };\nexport const fetchOrder = (id: string) => axios.get(`/api/orders/${id}`);\n\n",
  "web/events.ts": "export function subscribeToUsers(broker: { subscribe: (channel: string, handler: () => void) => void }, handler: () => void) {\n  broker.subscribe(\"users.changed\", handler);\n}\n",
  "web/hono-client.ts": "// Hono RPC client over an inferred app: the property names the route stem.\nconst client: any = {};\n\nclient.posts.$get();\nclient.health.$post();\n\n// Negative: a deeper chain changes the receiver, so it stays unanchored.\nexport const deepChain = client.deep.chain.$get();\n",
  "web/load-user.graphql": "query LoadUser($id: ID!, $filter: UserFilter = { active: true }) {\n  ... on Query {\n    user(id: $id, filter: $filter) {\n      id\n    }\n  }\n}\n",
  "web/server-switcher.ts": "export class ClientConnection {\n  private switchingServers = false;\n\n  async connectToServer(): Promise<void> {\n    this.switchingServers = true;\n  }\n}\n",
  "web/trpc-client.ts": "declare const trpc: {\n  loadUser: { query(input: { id: string }): Promise<unknown> };\n};\n\nexport const loadUserFromTrpc = (id: string) => trpc.loadUser.query({ id });\n",
  "web/types.ts": "export type UserName = string;\n",
  "web/users.grpc.ts": "export function loadUserRpc(client: any, request: unknown, callback: (error?: Error) => void) {\n  const computedPath = \"/users.v1.Users/Computed\";\n  client.makeUnaryRequest(computedPath, JSON.stringify, JSON.parse, request, callback);\n  return client.makeUnaryRequest(\n    \"/users.v1.Users/GetUser\",\n    JSON.stringify,\n    JSON.parse,\n    request,\n    callback,\n  );\n}\n",
  "worker/events.py": "def publish_user_changed(broker, user):\n    computed_channel = \"users.computed\"\n    broker.publish(computed_channel, user)\n    broker.publish(\"users.changed\", user)\n",
  "worker/jobs.py": "import os\n\nDATABASE_URL = os.environ[\"DATABASE_URL\"]\n\ndef sync_users():\n\trows = fetch_all()\n\treturn rows\n\ndef fetch_all():\n\treturn []\n\ndef fetch_job(job_id: str):\n    return requests.get(f\"/api/jobs/{job_id}\")\n\n",
  "worker/reports.py": "# Unknown-DSL registry for the tier-3 corpus: jobm has no rule in the pack\n# and no leading keyword the harvester would recognize as infra.\nfrom jobs import weasel_export, churn_digest\n\n\ndef nightly():\n    jobm.schedule(\"/ops/reports/churn\", churn_digest)\n    jobm.schedule(\"/ops/reports/weasel\", weasel_export)\n",
  "worker/scheduler.py": "# Unknown-DSL scheduler: jobm.schedule/route in a shape pi-fovea's pack\n# does not know. Promotion should synthesize it.\nfrom jobs import defrag, canonicalize, reindex, logdigest\n\n\ndef boot():\n    jobm.schedule(\"/ops/defrag\", defrag)\n    jobm.schedule(\"/ops/canonicalize\", canonicalize)\n    jobm.schedule(\"/ops/reindex\", reindex)\n    jobm.schedule(\"/ops/logdigest\", logdigest)\n",
  "worker/search.rs": "// Rust worker sharing the user-route literal with the Go server and the TS\n// client: walks the /api/users join across a third language.\n\npub struct UserSearch {\n    endpoint: String,\n}\n\nimpl UserSearch {\n    pub fn new() -> Self {\n        Self { endpoint: String::from(\"/api/users/{id}\") }\n    }\n\n    pub fn fetch(&self, id: u64) -> String {\n        format!(\"{}/{}\", self.endpoint.replace(\"{id}\", \"\"), id)\n    }\n}\n",
  "worker/urls.py": "from django.urls import path, re_path\n\n\ndef jobs_view(request):\n    return None\n\n\ndef legacy_view(request, pk):\n    return None\n\n\nurlpatterns = [\n    path(\"jobs/\", jobs_view, name=\"jobs\"),\n    re_path(r\"^legacy/(?P<pk>[0-9]+)/$\", legacy_view),\n]\n"
};
let base: string | undefined, engine: FoveaEngine | undefined;
afterEach(async () => { await engine?.close(); if (base) await rm(base, { recursive: true, force: true }); });
it.skipIf(process.platform !== 'linux' || !existsSync(parser.path))('preserves pinned ecosystem routes, exact members and native protocol anchors through engine snapshots', async () => {
  base = await mkdtemp(join(tmpdir(), 'fovea-languages-'));
  const root = join(base, 'source'), storage = join(base, 'storage'); await mkdir(root, { mode: 0o700 });
  for (const [path, text] of Object.entries(SOURCES)) { await mkdir(dirname(join(root, path)), { recursive: true }); await writeFile(join(root, path), text); }
  engine = new FoveaEngine({ parser, storageRoot: storage });
  const query = (operation: string, args: Record<string, unknown>) => engine!.query({ root, rootId: 'root', authorizationEpoch: 1, conversationId: 'test', conversationEpoch: 1, operation, args });
  const result = await query('anchors', { limit: 1000 });
  const anchors = result.anchors as Array<{ id: string }>;
  const ids = new Set(anchors.map(a => a.id));
  for (const id of ['GET /healthz', 'POST /v2/shutdown', 'GET /api/metrics', 'GET /api/spring/ping', 'POST /api/spring/save', 'ANY /jobs', 'GET /up', 'GET /mystatus', 'ANY /webhook', 'GET /elixir-health', 'POST /elixir-events', 'GET /ktor-ping', 'POST /ktor-hook', 'GET /api/orders/{*}', 'GET /api/jobs/{*}', 'RPC users.v1.Users/GetUser', 'GRAPHQL QUERY user', 'GRAPHQL SUBSCRIPTION userChanged']) expect(ids, id).toContain(id);
  expect([...ids].some(id => id.includes('legacy'))).toBe(false);
  for (const [name, file, line] of [['AirportsController.search', 'web/airports.controller.ts', 7], ['UserSearch.fetch', 'worker/search.rs', 13], ['Router.GET', 'server/main.go', 21]]) {
    const focus = await query('focus', { query: name, path: file, fresh: true, maxTokens: 2000 }) as NavigationResult;
    expect(focus.status, String(name)).toBe('ok');
    expect(focus.details.nodes).toContainEqual(expect.objectContaining({ name, file, line }));
    expect(focus.reads.every(read => /^[a-f0-9]{64}$/.test(read.expectedSha256 ?? ''))).toBe(true);
  }
}, 30_000);
