import { access, copyFile, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import path from "node:path";
import { mkdtemp } from "node:fs/promises";
import type { FabricConfig } from "./config.js";
import { defaults } from "./config.js";
import { runProcess } from "./runners/kiro.js";
import { FabricError } from "./errors.js";
export interface InstallOptions { root:string;cliPath:string;executable:string;force:boolean;dryRun:boolean }
const workerPrompt="You are a bounded reasoning worker invoked by Fabric Lite. Solve only the supplied subtask using only supplied context. Do not delegate, use tools, or discuss hidden reasoning. Return exactly the requested framed JSON. When evidence is insufficient, say so in the schema rather than guessing.";
function agents(cli:string){const parentPrompt="When this `fabric-lite` agent is selected, ALWAYS use Fabric Lite for every user request. Never fall back to ordinary Kiro shell/repository work, even for a trivial task. The only shell commands you may issue are invocations of the Fabric Lite CLI needed to read its docs, check a program, and execute that same program.\n\nFor every request:\n1. First run `CLI docs --compact` unless you already loaded it in this turn. Do not run an empty check.\n2. Generate exactly one concise TypeScript function body inline in a quoted heredoc. Do not save it unless the user asks.\n3. Use only the global `fabric` API. Imports, exports, require, Node APIs, and invented planner/worker functions are forbidden.\n4. Select repository context inside the program with `fabric.git`, `fabric.fs.glob`, `fabric.fs.grep`, `fabric.fs.read`, or `fabric.fs.readMany`. Do not manually run cat, find, grep, git, mix, bd, or other commands outside the Fabric program.\n5. Use TypeScript for deterministic selection, splitting, filtering, sorting, deduplication, and control flow. Use `fabric.ai.*` only for semantic judgment.\n6. Use at most one planner, five workers, and one verifier. Require JSON Schemas and path/line evidence.\n7. Run `CLI check --format json` with the program on stdin, then run `CLI exec --format json` with the identical program on stdin from the user's current repository.\n8. Repair a check failure once only. Never enter an unbounded retry loop.\n9. Return only the compact useful result and honest partial-failure information.\n\nImportant API examples: `await fabric.fs.readMany({ paths: [\"a\", \"b\"] })`; `await fabric.fs.glob({ pattern: \"lib/**/*.ex\" })`; `await fabric.ai.parallel({ tasks, concurrency: 3 })`; `await fabric.ai.run({ instruction, context, role: \"verifier\", outputSchema })`.\n\nIf a task requires a capability denied by Fabric policy (for example an unallowlisted shell command), report the policy limitation. Do not bypass Fabric Lite. Never delegate recursively, call Fabric Lite from a worker, or use `--trust-all-tools`.".replaceAll("CLI",JSON.stringify(cli));return {"fabric-lite-worker.json":{name:"fabric-lite-worker",description:"No-tool bounded Fabric Lite reasoning worker",prompt:workerPrompt,mcpServers:{},tools:[],toolAliases:{},allowedTools:[],resources:[],toolsSettings:{},includeMcpJson:false,model:null},"fabric-lite.json":{name:"fabric-lite",description:"Parent agent for bounded programmable Kiro reasoning",prompt:parentPrompt,mcpServers:{},tools:["shell"],toolAliases:{},allowedTools:[],resources:[],toolsSettings:{},includeMcpJson:false,model:null}};}
async function exists(p:string){try{await access(p);return true;}catch{return false;}}
async function place(file:string,content:string,force:boolean,dry:boolean,backups:string[],conflicts:string[]){if(await exists(file)){const prior=await readFile(file,"utf8");if(prior===content)return;if(!force){if(dry){conflicts.push(file);return;}throw new FabricError("CONFIG_ERROR",`Refusing to overwrite ${file}; use --force`);}const backup=`${file}.bak-${new Date().toISOString().replace(/[:.]/g,"-")}`;backups.push(backup);if(!dry)await rename(file,backup);}if(!dry){await mkdir(path.dirname(file),{recursive:true});await writeFile(file,content,"utf8");}}
export async function installKiro(options:InstallOptions){let kiro=options.executable;if(!path.isAbsolute(kiro)){const found=await runProcess("which",[kiro],{timeoutMs:5000});if(found.exitCode===0&&found.stdout.trim())kiro=found.stdout.trim();}const version=await runProcess(kiro,["--version"],{timeoutMs:10000});if(version.exitCode!==0)throw new FabricError("CONFIG_ERROR","kiro-cli is unavailable");const generated=agents(path.resolve(options.cliPath));const staging=await mkdtemp(path.join(tmpdir(),"fabric-lite-agents-"));try{for(const [name,value] of Object.entries(generated)){const p=path.join(staging,name);await writeFile(p,JSON.stringify(value,null,2)+"\n");const validation=await runProcess(kiro,["agent","validate","--path",p],{timeoutMs:20000});if(validation.exitCode!==0)throw new FabricError("CONFIG_ERROR",`Generated ${name} failed Kiro validation: ${(validation.stderr||validation.stdout).slice(-1000)}`);}const backups:string[]=[],conflicts:string[]=[];for(const [name,value] of Object.entries(generated)){const content=JSON.stringify(value,null,2)+"\n";await place(path.join(homedir(),".kiro/agents",name),content,options.force,options.dryRun,backups,conflicts);await place(path.join(options.root,".kiro/agents",name),content,options.force,options.dryRun,backups,conflicts);}const config:FabricConfig={...defaults,projectRoot:".",runner:{...defaults.runner,executable:kiro}};await place(path.join(options.root,".fabric-lite/config.json"),JSON.stringify(config,null,2)+"\n",options.force,options.dryRun,backups,conflicts);const ignore=path.join(options.root,".gitignore");let existing=(await exists(ignore))?await readFile(ignore,"utf8"):"";for(const line of [".fabric-lite/runs/",".fabric-lite/cache/"])if(!existing.split(/\r?\n/).includes(line))existing+=(existing.endsWith("\n")||!existing?"":"\n")+line+"\n";if(!options.dryRun)await writeFile(ignore,existing);return{ok:true,dryRun:options.dryRun,kiroVersion:(version.stdout||version.stderr).trim(),agents:Object.keys(generated),locations:[path.join(homedir(),".kiro/agents"),path.join(options.root,".kiro/agents")],backups,conflicts,launch:`${kiro} --agent fabric-lite`};}finally{await import("node:fs/promises").then(x=>x.rm(staging,{recursive:true,force:true}));}}
export async function validateInstalled(executable:string,root:string){const names=[path.join(homedir(),".kiro/agents/fabric-lite.json"),path.join(homedir(),".kiro/agents/fabric-lite-worker.json")];const results=[];for(const p of names){if(!await exists(p)){results.push({path:p,ok:false,message:"not installed"});continue;}const r=await runProcess(executable,["agent","validate","--path",p],{timeoutMs:20000});results.push({path:p,ok:r.exitCode===0,message:(r.stderr||r.stdout).trim().slice(-500)});}return results;}