import { describe,it,expect } from "vitest";
import { mkdtemp,writeFile,symlink,rm,mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createApi } from "../../src/api.js";
import { defaults,type FabricConfig } from "../../src/config.js";
import { FakeAiRunner } from "../../src/runners/fake.js";
async function fixture(){const root=await mkdtemp(path.join(tmpdir(),"fabric-api-"));await writeFile(path.join(root,"a.ts"),"one\ntwo token\nthree");await writeFile(path.join(root,".env"),"SECRET=x");await mkdir(path.join(root,"build"));await writeFile(path.join(root,"build/generated.ts"),"hidden");await mkdir(path.join(root,"coverage"));await writeFile(path.join(root,"coverage/report.ts"),"hidden");const config:FabricConfig={...defaults,projectRoot:root,budgets:{...defaults.budgets},filesystem:{...defaults.filesystem},shell:{...defaults.shell},runner:{...defaults.runner},output:{...defaults.output}};return{root,config};}
describe("deterministic API",()=>{it("reads, globs, greps and enforces policy",async()=>{const {root,config}=await fixture();try{const {fabric}=createApi(config,new FakeAiRunner());expect((await fabric.fs.read({path:"a.ts",startLine:2,endLine:2})).content).toBe("two token");expect(await fabric.fs.glob({pattern:"**/*.ts"})).toEqual(["a.ts"]);expect((await fabric.fs.grep({query:"token",paths:["a.ts"]})).matches[0].line).toBe(2);await expect(fabric.fs.read({path:"../outside"})).rejects.toThrow(/denied/);await expect(fabric.fs.read({path:".env"})).rejects.toThrow(/denied/);await expect(fabric.fs.write({path:"a.ts",content:"x"})).rejects.toThrow(/disabled/);}finally{await rm(root,{recursive:true,force:true});}});it("bounds shell stdout and stderr independently",async()=>{const {root,config}=await fixture();const command="printf 123456789; printf abcdefghi >&2";config.shell={...config.shell,enabled:true,allowedCommands:[command],maxOutputChars:5};try{const {fabric}=createApi(config,new FakeAiRunner());const result=await fabric.shell.run({command});expect(result).toMatchObject({stdout:"12345",stderr:"abcde",truncated:true});}finally{await rm(root,{recursive:true,force:true});}});it("rejects symlink escape",async()=>{const {root,config}=await fixture();const outside=await mkdtemp(path.join(tmpdir(),"fabric-out-"));await writeFile(path.join(outside,"x"),"x");await symlink(path.join(outside,"x"),path.join(root,"link"));try{const {fabric}=createApi(config,new FakeAiRunner());await expect(fabric.fs.read({path:"link"})).rejects.toThrow(/Symlink/);}finally{await rm(root,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});});

it("contains nested checkout paths at the project root",async()=>{const {root,config}=await fixture();try{await mkdir(path.join(root,"pi-fabric"));await writeFile(path.join(root,"pi-fabric/reference.ts"),"reference");const {fabric}=createApi(config,new FakeAiRunner());expect((await fabric.fs.read({path:"pi-fabric/reference.ts"})).content).toBe("reference");await expect(fabric.fs.read({path:"../pi-fabric/reference.ts"})).rejects.toThrow(/denied/);}finally{await rm(root,{recursive:true,force:true});}});