import { describe,it,expect } from "vitest";
import { execFile } from "node:child_process";
import { access,chmod,mkdtemp,writeFile,symlink,rm,mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createApi } from "../../src/api.js";
import { defaults,type FabricConfig } from "../../src/config.js";
import { FakeAiRunner } from "../../src/runners/fake.js";
import { loadPrompt } from "../../src/prompts.js";
const approve=async()=>"allow" as const;
async function fixture(){const root=await mkdtemp(path.join(tmpdir(),"fabric-api-"));await writeFile(path.join(root,"a.ts"),"one\ntwo token\nthree");await writeFile(path.join(root,".env"),"SECRET=x");await mkdir(path.join(root,"build"));await writeFile(path.join(root,"build/generated.ts"),"hidden");await mkdir(path.join(root,"coverage"));await writeFile(path.join(root,"coverage/report.ts"),"hidden");const config:FabricConfig={...defaults,projectRoot:root,budgets:{...defaults.budgets},filesystem:{...defaults.filesystem},git:{...defaults.git},shell:{...defaults.shell},runner:{...defaults.runner},output:{...defaults.output}};return{root,config};}
describe("deterministic API",()=>{it("reads, globs, greps and enforces policy",async()=>{const {root,config}=await fixture();try{const {fabric}=createApi(config,new FakeAiRunner());expect((await fabric.fs.read({path:"a.ts",startLine:2,endLine:2})).content).toBe("two token");expect(await fabric.fs.glob({pattern:"**/*.ts"})).toEqual(["a.ts"]);expect((await fabric.fs.grep({query:"token",paths:["a.ts"]})).matches[0].line).toBe(2);await expect(fabric.fs.read({path:"../outside"})).rejects.toThrow(/denied/);await expect(fabric.fs.read({path:".env"})).rejects.toThrow(/denied/);await expect(fabric.fs.write({path:"a.ts",content:"x"})).rejects.toThrow(/disabled/);}finally{await rm(root,{recursive:true,force:true});}});it("bounds shell stdout and stderr independently",async()=>{const {root,config}=await fixture();const command="printf 123456789; printf abcdefghi >&2";config.shell={...config.shell,enabled:true,allowedCommands:[command],maxOutputChars:5};try{const {fabric}=createApi(config,new FakeAiRunner(),{prompter:approve});const result=await fabric.shell.run({command});expect(result).toMatchObject({stdout:"12345",stderr:"abcde",truncated:true});}finally{await rm(root,{recursive:true,force:true});}});it("rejects symlink escape",async()=>{const {root,config}=await fixture();const outside=await mkdtemp(path.join(tmpdir(),"fabric-out-"));await writeFile(path.join(outside,"x"),"x");await symlink(path.join(outside,"x"),path.join(root,"link"));try{const {fabric}=createApi(config,new FakeAiRunner());await expect(fabric.fs.read({path:"link"})).rejects.toThrow(/Symlink/);}finally{await rm(root,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});});

it("uses the canonical JSON repair policy prefix",async()=>{const {root,config}=await fixture();const runner=new FakeAiRunner((_request,call)=>call===1?"not framed":{ok:true});try{const {fabric}=createApi(config,runner);const result=await fabric.ai.run({instruction:"answer",context:"",outputSchema:{type:"object",properties:{ok:{const:true}},required:["ok"]}});expect(result.repaired).toBe(true);expect(runner.calls[1]?.instruction.startsWith(`${loadPrompt("repair-json").trimEnd()}\n\nINVALID:\n`)).toBe(true);}finally{await rm(root,{recursive:true,force:true});}});

it("contains nested checkout paths at the project root",async()=>{const {root,config}=await fixture();try{await mkdir(path.join(root,"pi-fabric"));await writeFile(path.join(root,"pi-fabric/reference.ts"),"reference");const {fabric}=createApi(config,new FakeAiRunner());expect((await fabric.fs.read({path:"pi-fabric/reference.ts"})).content).toBe("reference");await expect(fabric.fs.read({path:"../pi-fabric/reference.ts"})).rejects.toThrow(/denied/);}finally{await rm(root,{recursive:true,force:true});}});

async function git(root:string,...args:string[]):Promise<string>{
 return await new Promise((resolve,reject)=>execFile("git",args,{cwd:root},(error,stdout,stderr)=>error?reject(new Error(stderr||error.message)):resolve(stdout.trim())));
}

async function gitFixture(){
 const value=await fixture();
 await git(value.root,"init","-q");
 await git(value.root,"config","user.name","Fabric Test");
 await git(value.root,"config","user.email","fabric@example.invalid");
 await git(value.root,"add","--","a.ts");
 await git(value.root,"-c","core.hooksPath=/dev/null","-c","commit.gpgSign=false","commit","-q","--no-verify","--no-gpg-sign","-m","initial");
 return value;
}

describe("bounded local Git commits",()=>{
 it("reads history, objects, branches, and remotes without mutation",async()=>{const {root,config}=await gitFixture();try{const {fabric}=createApi(config,new FakeAiRunner());expect((await fabric.git.log({maxCount:1})).text).toContain("initial");expect((await fabric.git.show({path:"a.ts"})).text).toContain("two token");expect(await fabric.git.branches()).toEqual(expect.arrayContaining([expect.stringContaining("main")]));expect(await fabric.git.remotes()).toEqual([]);expect(fabric.git.push).toBeUndefined();}finally{await rm(root,{recursive:true,force:true});}});
 it("denies commits by default and exposes no push API",async()=>{const {root,config}=await gitFixture();try{await writeFile(path.join(root,"a.ts"),"changed");const {fabric}=createApi(config,new FakeAiRunner());await expect(fabric.git.commit({message:"test: denied",paths:["a.ts"]})).rejects.toMatchObject({code:"POLICY_DENIED"});expect(fabric.git.push).toBeUndefined();}finally{await rm(root,{recursive:true,force:true});}});
 it("commits only explicit paths when independently enabled",async()=>{const {root,config}=await gitFixture();config.git.allowCommit=true;try{await writeFile(path.join(root,".gitattributes"),"a.ts filter=evil\n");await git(root,"config","filter.evil.clean","sh -c 'touch filter-ran; cat'");const hook=path.join(root,".git/hooks/pre-commit");await writeFile(hook,"#!/bin/sh\ntouch hook-ran\n");await chmod(hook,0o755);await writeFile(path.join(root,"a.ts"),"committed");await writeFile(path.join(root,"other.ts"),"not committed");const {fabric}=createApi(config,new FakeAiRunner(),{prompter:approve});const result=await fabric.git.commit({message:"test: bounded local commit",paths:["a.ts"]});expect(result).toMatchObject({message:"test: bounded local commit",paths:["a.ts"]});expect(result.hash).toMatch(/^[0-9a-f]{40}$/);expect(await git(root,"show","--format=","--name-only","HEAD")).toBe("a.ts");expect(await git(root,"status","--short","--","other.ts")).toContain("?? other.ts");await expect(access(path.join(root,"filter-ran")).then(()=>true,()=>false),"clean filter must not execute").resolves.toBe(false);await expect(access(path.join(root,"hook-ran")).then(()=>true,()=>false),"commit hook must not execute").resolves.toBe(false);}finally{await rm(root,{recursive:true,force:true});}});
 it("requires explicit safe paths and safe bounded messages",async()=>{const {root,config}=await gitFixture();config.git.allowCommit=true;try{const {fabric}=createApi(config,new FakeAiRunner());await expect(fabric.git.commit({message:"test: empty",paths:[]})).rejects.toMatchObject({code:"POLICY_DENIED"});await expect(fabric.git.commit({message:" bad",paths:["a.ts"]})).rejects.toMatchObject({code:"POLICY_DENIED"});await expect(fabric.git.commit({message:"test: escape",paths:["../outside"]})).rejects.toMatchObject({code:"POLICY_DENIED"});await expect(fabric.git.commit({message:"test: metadata",paths:[".git/config"]})).rejects.toMatchObject({code:"POLICY_DENIED"});}finally{await rm(root,{recursive:true,force:true});}});
 it("refuses pre-existing staged changes",async()=>{const {root,config}=await gitFixture();config.git.allowCommit=true;try{await writeFile(path.join(root,"staged.ts"),"staged");await git(root,"add","--","staged.ts");await writeFile(path.join(root,"a.ts"),"requested");const {fabric}=createApi(config,new FakeAiRunner(),{prompter:approve});await expect(fabric.git.commit({message:"test: reject mixed index",paths:["a.ts"]})).rejects.toThrow(/pre-existing staged/);}finally{await rm(root,{recursive:true,force:true});}});
 it("keeps destructive shell commands denied when commits are enabled",async()=>{const {root,config}=await gitFixture();config.git.allowCommit=true;try{const {fabric}=createApi(config,new FakeAiRunner());for(const command of ["rm -rf .","kubectl delete namespace production","psql -c 'drop database app'","git push origin main"])await expect(fabric.shell.run({command})).rejects.toMatchObject({code:"POLICY_DENIED"});}finally{await rm(root,{recursive:true,force:true});}});
});

describe("read-only inspection policy",()=>{
 it("constructs fixed read-only argv for supported inspectors",async()=>{const {root,config}=await fixture();const bin=path.join(root,"bin");await mkdir(bin);const probe=path.join(bin,"probe");await writeFile(probe,"#!/bin/sh\nprintf '%s\\n' \"$0|$*\"\n");await chmod(probe,0o755);for(const name of ["psql","redis-cli","sqlite3","kubectl","terraform"])await symlink(probe,path.join(bin,name));const prior=process.env.PATH;process.env.PATH=`${bin}:${prior??""}`;try{const {fabric}=createApi(config,new FakeAiRunner(),{prompter:approve});expect((await fabric.inspect.postgres({query:"SELECT 1"})).stdout).toContain("BEGIN READ ONLY");expect((await fabric.inspect.redis({command:"GET",args:["key"]})).stdout).toContain("GET key");expect((await fabric.inspect.sqlite({path:"a.ts",query:"SELECT 1"})).stdout).toContain("-readonly -safe");expect((await fabric.inspect.kubernetes({operation:"get",resource:"pods",namespace:"default"})).stdout).toContain("get pods -o yaml");expect((await fabric.inspect.terraform({operation:"validate"})).stdout).toContain("validate -json");}finally{process.env.PATH=prior;await rm(root,{recursive:true,force:true});}});
 it("rejects mutating and operational PostgreSQL statements",async()=>{const {root,config}=await fixture();try{const {fabric}=createApi(config,new FakeAiRunner());for(const query of ["DELETE FROM users","SELECT pg_terminate_backend(1)","SELECT 1; DROP TABLE users","EXPLAIN ANALYZE DELETE FROM users","WITH gone AS (DELETE FROM users RETURNING *) SELECT * FROM gone"])await expect(fabric.inspect.postgres({query})).rejects.toMatchObject({code:"POLICY_DENIED"});}finally{await rm(root,{recursive:true,force:true});}});
 it("rejects Redis mutation and administration commands",async()=>{const {root,config}=await fixture();try{const {fabric}=createApi(config,new FakeAiRunner());for(const command of ["SET","DEL","FLUSHALL","EVAL","PUBLISH","CONFIG","SHUTDOWN"])await expect(fabric.inspect.redis({command,args:["key"]})).rejects.toMatchObject({code:"POLICY_DENIED"});await expect(fabric.inspect.redis({command:"MEMORY",args:["PURGE"]})).rejects.toMatchObject({code:"POLICY_DENIED"});}finally{await rm(root,{recursive:true,force:true});}});
 it("rejects SQLite mutation statements",async()=>{const {root,config}=await fixture();try{const {fabric}=createApi(config,new FakeAiRunner());for(const query of ["UPDATE items SET value=1","PRAGMA journal_mode=WAL","ATTACH DATABASE 'x' AS other","SELECT 1; DELETE FROM items"])await expect(fabric.inspect.sqlite({path:"a.ts",query})).rejects.toMatchObject({code:"POLICY_DENIED"});}finally{await rm(root,{recursive:true,force:true});}});
 it("allows only fixed Kubernetes reads and denies sensitive resources",async()=>{const {root,config}=await fixture();try{const {fabric}=createApi(config,new FakeAiRunner());for(const operation of ["delete","apply","exec","patch","scale","port-forward"])await expect(fabric.inspect.kubernetes({operation,resource:"pods"})).rejects.toMatchObject({code:"POLICY_DENIED"});await expect(fabric.inspect.kubernetes({operation:"get",resource:"secrets"})).rejects.toMatchObject({code:"POLICY_DENIED"});await expect(fabric.inspect.kubernetes({operation:"get",resource:"pods",name:"--all-namespaces"})).rejects.toMatchObject({code:"POLICY_DENIED"});}finally{await rm(root,{recursive:true,force:true});}});
 it("allows only fixed Terraform reads",async()=>{const {root,config}=await fixture();try{const {fabric}=createApi(config,new FakeAiRunner());for(const operation of ["plan","apply","destroy","import","state-rm","force-unlock"])await expect(fabric.inspect.terraform({operation})).rejects.toMatchObject({code:"POLICY_DENIED"});}finally{await rm(root,{recursive:true,force:true});}});
});